### ISSUE TITLE
Example code in the readme executes with errors 

### ISSUE THREAD

**Issue by melezhik** [grondilu/elliptic-curves-raku#3]
Please see this build log - https://ci.sparrowhub.io/report/2334

the very first snippet is extracted from the readme and executed with errors …

**Comment by grondilu** [comment]
that constant was removed from the code previously but I forgot to remove it from the synopsis.

Done with a56a913b8398661e57eaa51401473fe4460225de

**Comment by melezhik** [comment]
Hi! I merged your changes in my branch the code snippet still fails ( now it’s different  error ) - https://ci.sparrowhub.io/report/2352 , but maybe it’s ok …
